# Generated by Django 4.2 on 2023-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
