# Generated by Django 4.2 on 2023-05-20 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_bloodrequest_blood_group_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='campagain',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
